---
- name: Create Tower Organizations
  tower_organization:
    name: "{{ item.name }}"
    description: "{{ item.description }}"
    tower_password: "{{ tower_password }}"
    tower_username: "{{ tower_username }}"
    tower_host: "{{ tower_host }}"
  with_items: "{{ tower_orgs }}"
