---
- name: Delete Tower Organizations
  tower_organization:
    name: "{{ item.name }}"
    tower_password: "{{ tower_password }}"
    tower_username: "{{ tower_username }}"
    tower_host: "{{ tower_host }}"
    state: absent
  with_items: "{{ tower_orgs }}"
