---
- name: add Tower Users
  tower_user:
    username: "{{ item.username }}"
    password: "{{ item.password }}"
    email: "{{ item.email|default(item.username + '@example.com') }}"
    last_name: "{{ item.last_name|default(item.username) }}"
    first_name: "{{ item.first_name|default(item.username) }}"
    state: present
    superuser: "{{ item.is_admin|default(False) }}"
    tower_host: "{{ tower_host }}"
    tower_username: "{{ tower_username }}"
    tower_password: "{{ tower_password }}"
  with_items: "{{ tower_users }}"

- name: add Tower users to the appropriate organization
  tower_role:
    role: "{{ item.org_role|default('member')}}"
    user: "{{ item.username }}"
    organization: "{{ item.organization|default('Default') }}"
  with_items: "{{ tower_users }}"
