---
- name: delete Tower Users
  tower_user:
    username: "{{ item.username }}"
    state: absent
    tower_host: "{{ tower_host }}"
    tower_username: "{{ tower_username }}"
    tower_password: "{{ tower_password }}"
  with_items: "{{ tower_users }}"
